[tool.pytest.ini_options]
minversion = "7.0"
asyncio_mode = "auto"
python_files = [
    "test_*.py",
]
filterwarnings = [
    "ignore::DeprecationWarning:aiohttp_json_rpc",
    "ignore::DeprecationWarning:aiohttp",
]
env_files = [
    ".env"
]

[tool.mypy]
check_untyped_defs = true
mypy_path = ["/home/xentrick/dev/python-replay-parser"]

[tool.isort]
profile = "black"

[tool.ruff]
line-length = 200
indent-width = 4
exclude = ["scripts/", "data/"]

[tool.ruff.lint]
select = ["E", "F", "B", "C4", "SIM", "PTH", "TID", "ASYNC"]
ignore = ["B904","SIM103", "SIM108"]

[tool.codespell]
ignore-words-list = "ptd,oce,nd,cros,recuse,checkin"
